### ISSUE TITLE
Missing HASSPIFFS directive in BolbroWebServer.h

### ISSUE THREAD

**Issue by Nkawu** [HarrysLapTimer/WeatherStationOne#1]
`weatherbase.ino` fails to compile on ESP32, unable to find method `loadFromSpiffs`. I had to add the `HASSPIFFS` directive to `BolbroWebServer.h` to get it to compile.

Remove directives block from `BolbroWebServer.cpp` (optional I suppose):
```c++
#ifdef ESP_PLATFORM // ESP32
#	define HASSPIFFS 1
#else
#	define HASSPIFFS 0
#endif
```

Add `HASSPIFFS` directives to `BolbroWebServer.h`:
```c++
#ifdef ESP_PLATFORM // ESP32
#	include <WebServer.h>
#	define HASSPIFFS 1
#else
#	include <ESP8266WebServer.h>
#	define WebServer ESP8266WebServer
#	define HASSPIFFS 0
#endif
```

Also the presence of `Sun.c` is causing a class related compilation failure, had to remove the file.

**Comment by HarrysLapTimer** [comment]
Thanks. Pushed the latest version fixing the HASSPIFFS definition. I will have a look into Sun soon. :-)

**Comment by HarrysLapTimer** [comment]
Sun.c has been a migration artifact and has been removed. The code is in Sun.cpp now.

**Comment by Nkawu** [comment]
Thanks Harry! I'm still waiting for my ESP32s to arrive from China, looking at the code in the meantime.
