### ISSUE TITLE
Problem beim compelieren

### ISSUE THREAD

**Issue by bodo328** [HarrysLapTimer/WeatherStationOne#3]
Hallo ein tolles Projekt
leider habe ich ein Problem beim kompetieren ich bekomme folgende Fehlermeldung:
:\Program Files (x86)\Arduino\libraries\Bolbro\Bolbro.cpp: In member function 'void BolbroClass::onWiFiEvent(system_event_id_t)':
C:\Program Files (x86)\Arduino\libraries\Bolbro\Bolbro.cpp:540:14: error: 'ARDUINO_EVENT_WIFI_STA_START' was not declared in this scope
         case ARDUINO_EVENT_WIFI_STA_START:
              ^
C:\Program Files (x86)\Arduino\libraries\Bolbro\Bolbro.cpp:544:14: error: 'ARDUINO_EVENT_WIFI_STA_CONNECTED' was not declared in this scope
         case ARDUINO_EVENT_WIFI_STA_CONNECTED:
              ^
C:\Program Files (x86)\Arduino\libraries\Bolbro\Bolbro.cpp:548:14: error: 'ARDUINO_EVENT_WIFI_STA_GOT_IP6' was not declared in this scope
         case ARDUINO_EVENT_WIFI_STA_GOT_IP6:
              ^
C:\Program Files (x86)\Arduino\libraries\Bolbro\Bolbro.cpp:551:14: error: 'ARDUINO_EVENT_WIFI_STA_GOT_IP' was not declared in this scope
         case ARDUINO_EVENT_WIFI_STA_GOT_IP:
              ^
C:\Program Files (x86)\Arduino\libraries\Bolbro\Bolbro.cpp:554:14: error: 'ARDUINO_EVENT_WIFI_STA_DISCONNECTED' was not declared in this scope
         case ARDUINO_EVENT_WIFI_STA_DISCONNECTED:
              ^
exit status 1
 
Welche Einstellungen muss ich noch ändern

**Comment by HarrysLapTimer** [comment]
Das sind die für ESP32 Boards definierten WIFI Konstanten. Ich nutze die Bolbro Bibliothek für alle meine IoT Projekte. Dabei verwende ich ESP32 Developer Boards oder ein ESP8266 Mini Board. Die Bibliothek ist aber nicht für alle denkbaren Boards vorbereitet, wenn man also ein anderes verwendet, muss man den Code anpassen. Meine ESP32 Boards werden anhand der vordefinierten Variable ESP_PLATFORM erkannt. Ist die nicht definiert, wird der Code für das ESP8266 verwendet.

Bei Dir scheint ESP_PLATFORM definiert zu sein, es müsste also ein ESP32 sein? Vielleicht ist eine alte Board-Version installiert?

**Comment by bodo328** [comment]
Ja es ist ein Esp32. Ich benutze in der Arduino Version 1.8.19 ein esp32dev hat bis jetzt immer funktioniert. Es sind alle Updates Installiert. Sobald ich auf überprüfe/kompilieren gehe kommt die Fehlermeldung. Habe mal andere Boards ausprobiert aber immer das gleiche. Auch wenn ich die weatherstation nehme gleiche Meldung. 
Ich habe gerade spaßeshalber einen esp8266 als Board genommen geht auch nicht

**Comment by bodo328** [comment]
Wo finde ich die ESP_PLATFORM

**Comment by HarrysLapTimer** [comment]
ESP_PLATFORM wird im Code nur genutzt und wird vom Compiler für den ESP32 Board Typ vordefiniert. Das ist nicht das Problem, weil auf die Symbole wie ARDUINO_EVENT_WIFI_STA_START ja nur referenziert wird, wenn ESP_PLATFORM definiert ist. Es ist also für Deine Umgebung auch vordefiniert.

In meiner ESP32 Library ist ARDUINO_EVENT_WIFI_STA_START in der Datei WiFiGeneric.h definiert und diese Datei wird wiederum durch #	include <WiFi.h> in Bolbro.h inkludiert. Bitte gegenprüfen und ggf. eine neue Library installieren. Alternativ muss halt der Code für die WiFi-Verbindungsaufnahme für Dein Board angepasst werden, das kann ich Dir aber nicht abnehmen. ;-)

**Comment by bodo328** [comment]
ok Danke für dein Bemühen. Ich bekomme es nicht hin so fit bin ich nicht das ich es ohne Hilfe ändern kann. wenn ich weis wo und was wirdes wohl gehen.

Viele Grüße von mir

**Comment by HarrysLapTimer** [comment]
Schaue mal hier: https://forum.arduino.cc/t/library-conflicts-between-esp32-and-standard-arduino-libraries/469500
Bei mir wird beim Kompilieren auch gemeldet, dass zwei WiFi.h Dateien gefunden wurden. Da wird aber die ESP32 Variante verwendet. In der Standard Arduino WiFi.h Datei sind die genannten Symbole nicht definiert, das ist ESP32 only.
